name: Compile T0 Book
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  compile-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Run book compiler script
      run: python 2/combine_tex_book.py
    - name: Commit generated book
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add T0_Book_En.tex
        git commit -m 'Auto-generate T0 Book from English LaTeX files' || echo 'No changes to commit'
        git push