#!/usr/bin/env python3
"""Spectral check of the OPH twelve-port carrier.

Reads the seam list from native_trace.json (ipi_native_baseline_2026-09-14)
or falls back to the canonical icosahedron graph. Computes the spectrum of the
seam-mean averaging operator W = D^{-1} A and the graph Laplacian L = D - A in
exact arithmetic (sympy), then checks the replayed sweep operator against the
trace. No physical claim is made; this only answers the question whether the
carrier spectrum admits a rational mode index.

Usage:  python3 spectrum_icosahedral_carrier.py [path/to/native_trace.json]
"""
from __future__ import annotations

import itertools
import json
import sys
from fractions import Fraction as F
from pathlib import Path

import sympy as sp

# ----------------------------------------------------------------------
# 1. Seam list
# ----------------------------------------------------------------------

def load_edges(trace: Path | None):
    if trace and trace.exists():
        data = json.loads(trace.read_text())
        edges = [tuple(e) for e in data["seams"]]
        return edges, data
    # canonical icosahedron: vertices (0,±1,±φ) cyclic, adjacency by distance 2
    phi = sp.GoldenRatio
    verts = []
    for s1, s2 in itertools.product((1, -1), repeat=2):
        verts += [(0, s1, s2 * phi), (s1, s2 * phi, 0), (s2 * phi, 0, s1)]
    edges = []
    for i, j in itertools.combinations(range(12), 2):
        d2 = sum((a - b) ** 2 for a, b in zip(verts[i], verts[j]))
        if sp.simplify(d2 - 4) == 0:
            edges.append((i, j))
    return edges, None


trace_path = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("native_trace.json")
edges, trace = load_edges(trace_path)
n = 12
assert len(edges) == 30, len(edges)

# ----------------------------------------------------------------------
# 2. Exact spectrum of A, W = A/5, L = 5I - A
# ----------------------------------------------------------------------
A = sp.zeros(n, n)
for i, j in edges:
    A[i, j] = 1
    A[j, i] = 1
deg = [sum(A.row(i)) for i in range(n)]
assert all(d == 5 for d in deg), deg          # 5-regular
W = A / 5
L = 5 * sp.eye(n) - A

specA = A.eigenvals()                          # {value: multiplicity}
s5 = sp.sqrt(5)
expected_A = {5: 1, s5: 3, -1: 5, -s5: 3}
assert {sp.nsimplify(k): v for k, v in specA.items()} == expected_A, specA

print("Carrier: 12 ports, 30 seams, 5-regular (icosahedral)")
print("Spectrum of A          :", {str(k): v for k, v in specA.items()})
print("Spectrum of W = A/5    :", {str(sp.nsimplify(k / 5)): v for k, v in specA.items()})
print("Spectrum of L = 5I - A :", {str(sp.nsimplify(5 - k)): v for k, v in specA.items()})

# ----------------------------------------------------------------------
# 3. Rationality of the mode index
# ----------------------------------------------------------------------
nontrivial = [sp.nsimplify(5 - k) for k in specA if k != 5]   # Laplacian values
rational = [mu for mu in nontrivial if mu.is_rational]
irrational = [mu for mu in nontrivial if not mu.is_rational]
assert rational == [6], rational
assert set(irrational) == {5 - s5, 5 + s5}
# field generated by the spectrum is Q(sqrt5), degree 2 over Q
K = sp.QQ.algebraic_field(s5)
print("Field generated by spectrum: Q(sqrt(5)), degree", K.ext.minpoly.degree())
print("Rational non-trivial Laplacian eigenvalue(s):", rational, "(mult 5)")
print("Irrational eigenvalues:", irrational, "(mult 3 each)")
print("Conclusion: no common rational ground value; sqrt(5) is irreducible.")

# ----------------------------------------------------------------------
# 4. Consistency with the exact trace (sweep operator, seed 7)
# ----------------------------------------------------------------------
if trace:
    def seam_matrix(i, j):
        M = sp.eye(n)
        M[i, i] = M[i, j] = M[j, i] = M[j, j] = sp.Rational(1, 2)
        return M

    case = trace["cases"][0]
    assert case["name"] == "pulse_repair_seed7"
    schedule = [tuple(e["seam"]) for e in case["events"]]
    assert len(schedule) == 300 and all(sorted(schedule[k*30:(k+1)*30]) == sorted(edges) for k in range(10))

    # replay exactly and compare with the recorded final state
    state = sp.Matrix([F(x) for x in case["initial_state"]])
    for e in schedule:
        state = seam_matrix(*e) * state
    recorded = sp.Matrix([sp.Rational(x) for x in case["events"][-1]["state_after"]])
    assert state == recorded, "replay differs from trace"
    total = sum(state)
    centered = sum(x**2 for x in state) - total**2 / n
    assert str(centered) == case["summary"]["centered_squared_norm_final"]
    print("Exact replay of 300 updates (seed 7) matches trace; centered residual =",
          float(centered))

    # one-sweep operator (first sweep): spectral radius 1, second eigenvalue small
    P = sp.eye(n)
    for e in reversed(schedule[:30]):
        P = seam_matrix(*e) * P
    ev = sorted(abs(complex(v)) for v in sp.Matrix(P).evalf().eigenvals())
    print("First-sweep operator: |lambda| max = %.6f, second = %.6f (non-symmetric product)"
          % (ev[-1], ev[-2]))
    assert abs(ev[-1] - 1) < 1e-9 and ev[-2] < 0.5

# ----------------------------------------------------------------------
# 5. Block damping rates of the expected single-seam update E[M] = I - L/60
# ----------------------------------------------------------------------
rates = {"3-block (5-sqrt5)": 1 - (5 - s5) / 60,
         "5-block (6)":       sp.Rational(9, 10),
         "3'-block (5+sqrt5)": 1 - (5 + s5) / 60}
assert sp.simplify(rates["3-block (5-sqrt5)"] - (55 + s5) / 60) == 0
assert sp.simplify(rates["3'-block (5+sqrt5)"] - (55 - s5) / 60) == 0
diff = sp.simplify(rates["3-block (5-sqrt5)"] - rates["3'-block (5+sqrt5)"])
ratio = sp.nsimplify(rates["3-block (5-sqrt5)"] / rates["3'-block (5+sqrt5)"])
assert diff == s5 / 30
print("E[M] = I - L/60 block eigenvalues:", {k: (str(v), float(v)) for k, v in rates.items()})
print("3 vs 3': difference = sqrt5/30 = %.6f, ratio = %.6f (a difference, not a factor)"
      % (float(diff), float(ratio)))

print("ALL CHECKS PASSED")
